### PR TITLE
Fix the proxy_bypass_registry function all returning true in some cases.

### PR DESCRIPTION
**Pull request by flysee**
With the context code,i think we should avoid this situation with empty strings,thx!

### CODE REVIEW

**Comment by sigmavirus24** [comment]
There's no clear description of a bug, how to reproduce or even tests to show this fixes something. Further you speak of empty strings and are filtering on None which are not the same thing.

**Comment by flysee** [comment]
The value of proxyOverride is controlled by a third-party program on the computer, so it is not controllable.
For example, when I use fiddler on my computer, this value is `<-loopback>;`.(Not all computers)
When proxyOverride splits, it's equal to `['<-loopback>', '']`.
So `re.match('', host, re.I)` will return true,that bypassing the proxy.

And filter(function, iterable) is equivalent to the generator expression (item for item in iterable if item) if function is None,that is, all elements of iterable that are false are removed.
Ref:https://docs.python.org/3/library/functions.html#filter

I think should be avoided for code robustness.

**Review by iamxiwang — APPROVED** [review]

**Review by ravi-kale — APPROVED** [review]

**Comment by aaronhua123** [comment]
> The value of proxyOverride is controlled by a third-party program on the computer, so it is not controllable. For example, when I use fiddler on my computer, this value is `<-loopback>;`.(Not all computers) When proxyOverride splits, it's equal to `['<-loopback>', '']`. So `re.match('', host, re.I)` will return true,that bypassing the proxy.
> 
> And filter(function, iterable) is equivalent to the generator expression (item for item in iterable if item) if function is None,that is, all elements of iterable that are false are removed. Ref:https://docs.python.org/3/library/functions.html#filter
> 
> I think should be avoided for code robustness.

Yes, I also noticed this situation. This wastes a lot of my time discovering this problem. ProxyOverride sometimes ends with a semicolon and is difficult to reproduce. But it has not yet been merged into the main branch.

**Comment by flysee** [comment]
> > The value of proxyOverride is controlled by a third-party program on the computer, so it is not controllable. For example, when I use fiddler on my computer, this value is `<-loopback>;`.(Not all computers) When proxyOverride splits, it's equal to `['<-loopback>', '']`. So `re.match('', host, re.I)` will return true,that bypassing the proxy.
> > And filter(function, iterable) is equivalent to the generator expression (item for item in iterable if item) if function is None,that is, all elements of iterable that are false are removed. Ref:https://docs.python.org/3/library/functions.html#filter
> > I think should be avoided for code robustness.
> 
> Yes, I also noticed this situation. This wastes a lot of my time discovering this problem. ProxyOverride sometimes ends with a semicolon and is difficult to reproduce. But it has not yet been merged into the main branch.

I'm glad someone else is having the same problem as me, but I also hope that no one will waste time on this issue in the future, haha.

**Comment by sigmavirus24** [comment]
@flysee can you add tests for this change so it does not regress?

**Comment by flysee** [comment]
> @flysee can you add tests for this change so it does not regress?

Of course, test cases have been added.

**Review by sigmavirus24 — APPROVED** [review]
@nateprewitt thoughts on getting this into the next release? 2.32 iirc?

**Review by nateprewitt — APPROVED** [review]
Yeah, this seems reasonable. I've put it on the 2.32.0 milestone.

**Pull request merged**
