### PR TITLE
Add back logo

### LINKED ISSUE #5926: Restore logo
@kennethreitz mentioned he had a single condition for transferring stewardship for this repository:

> When I transferred the project to the PSF, per textual agreement with @ewdurbin, my only requirement was that the logo stayed in place.

I therefore assume that the removal in #5562 (along other images) was accidental and this will swiftly rectified. I’ll do a PR.

### PR DESCRIPTION
**Pull request by flying-sheep**
Fixes #5926

I’m not a web designer, so the positioning might be adjusted.

However, the logo’s restoration should take priority over bikeshedding.

### CODE REVIEW

**Comment by mik-laj** [comment]
Should we add it to README.md also?

**Comment by flying-sheep** [comment]
I think so, and this PR does it (I updated the title to reflect that). Some people will never see the sphinx docs page, so it makes sense to have it in both locations.

**Review by mik-laj — APPROVED** [review]

**Comment by nateprewitt** [comment]
Hi @flying-sheep, we already have a PR open for this in #5923. Thanks for the contribution though.

**Comment by flying-sheep** [comment]
Oh, sorry, didn’t see that one!

**Pull request closed without merging**
