### PR TITLE
docs - clarify json() error exception for Python 3

### PR DESCRIPTION
**Pull request by wesinator**
python 3 exception is `JSONDecodeError:  Expecting value: line 1 column 1 (char 0)`

https://github.com/psf/requests/issues/4908

### CODE REVIEW

**Comment by kennethreitz** [comment]
This should absolutely not be merged.

**Comment by wesinator** [comment]
> This should absolutely not be merged.

why ?

**Comment by nateprewitt** [comment]
Hi @wesinator, I think we’ll pass on this one. If you take a look at Python 3, you’ll find that JSONDecodeError to be a ValueError. Including the simplejson stack trace doesn’t provide information specific to Requests, just general stacktrace handling.

**Comment by wesinator** [comment]
> 
> 
> Hi @wesinator, I think we’ll pass on this one. If you take a look at Python 3, you’ll find that JSONDecodeError to be a ValueError. Including the simplejson stack trace doesn’t provide information specific to Requests, just general stacktrace handling.

ok, fair. I know it's general stacktrace

thanks,

**Pull request closed without merging**
