### PR TITLE
Added a warning when stripping authentication from requests on a redirect

### PR DESCRIPTION
**Pull request by kmaork**
Hello!
After seeing this [question](https://stackoverflow.com/questions/60358216/python-requests-post-request-dropping-authorization-header), I thought a warning should be added when authentication is stripped from redirected requests, in order to save users a significant amount of debugging time.
Apparently the matter has already been discussed in [this issue](https://github.com/psf/requests/issues/2949), and it has been agreed upon that *some* message should be passed to the user, like a debug log or a warning. But requests still does not use logs, and it seems people are still confused by this.
Maybe it is time to add a warning?

### CODE REVIEW

**Comment by kmaork** [comment]
Does the PR need another review?

**Comment by kmaork** [comment]
Can we make progress with this? 🙂 @yanz-androidify

**Comment by Ezhvsalate** [comment]
Great PR, lost an hour today trying to understand why my service was broken after moved to OpenShift (it internally redirected requests). This warning could have helped me a lot.

**Comment by SaritNike** [comment]
This PR would come really handy @yanz-androidify @kmaork why does it still say that the merging is blocked? How can we get someone with write access to review and approve this PR? It's waiting since May.  
The current state of requests makes it nearly unusable for me when the host is on some cloud provider's server which does automatic redirects on ingress.

**Comment by scorchio** [comment]
I've lost a good 2 hours trying to find out what's wrong when I was playing around with PyGithub, which is using requests under the hood.

@nateprewitt, could you please take a look and provide some feedback? It would be great if requests could be a bit more helpful in such scenarios.

**Comment by yannicschroeer** [comment]
Please add this. The current behavior is annoyingly implicit!

**Comment by kmaork** [comment]
Hey @nateprewitt , @sigmavirus24 , @sethmlarson - this PR was approved ages ago by @yanz-androidify but seems to have been forgotten since. Any chance of it getting reviewed?

**Comment by sigmavirus24** [comment]
@kmaork I don't see an approval from that account nor are they a maintainer (nor does that account seem to exist any longer).

As it stands, yes this can be annoyingly secure and hidden from the user but this usage of warnings is inappropriate for the solution. It's not the right mechanism and it will result in more issues generated here than users helped.

**Pull request closed without merging**
