### PR TITLE
Allow charset normalizer >=2 and <4

### PR DESCRIPTION
**Pull request by deedy5**
charset-normalizer 3.0.0 has been released.

### CODE REVIEW

**Review by sigmavirus24 — CHANGES_REQUESTED** [review]
There's little value to raising the lower bound and much more grief for users

**Comment by deedy5** [comment]
v3.0.0 up to 4x faster than v2.1
https://github.com/Ousret/charset_normalizer/releases/tag/3.0.0
https://charset-normalizer.readthedocs.io/en/latest/community/speedup.html

**Comment by sigmavirus24** [comment]
Yes, and given this isn't critical path for most users it's not critical to force people through a major version change to get that. If they use character detection of any sort and need performance they can force it to upgrade, but that's not our job

**Review by sigmavirus24 — APPROVED** [review]

**Review by sethmlarson — APPROVED** [review]

**Review by nateprewitt — APPROVED** [review]

**Comment by nateprewitt** [comment]
Thanks @deedy5!

**Comment by arossert** [comment]
Any estimation on a new release with this fix?

**Comment by jimbudarz** [comment]
It looks like versions of `charset_normalizer` below 3.0.1 are [no longer available](https://pypi.org/project/charset-normalizer/#history) on pypi, so it's not possible to pip install `requests` until a new release is published.

**Comment by nateprewitt** [comment]
This should now be available on PyPI in Requests 2.28.2.

**Pull request merged**
