### PR TITLE
Rewrite version checks and split using iteration protocol

### PR DESCRIPTION
**Pull request by oyeyipo**
Make use of `map` and sequence unpacking in an iteration context to make the codes a little bit declarative.

### CODE REVIEW

**Comment by nateprewitt** [comment]
Hi @oyeyipo, thanks for the PR. This is actually a duplicate of #5334 and #5281. Please make sure to check open and closed PRs before opening new ones.

**Comment by oyeyipo** [comment]
Hey @nateprewitt, thanks for the suggestion. Did do a cursory scan of opened pr first page. Now, took a practical look at search techniques at [github pr search](https://docs.github.com/en/enterprise-cloud@latest/search-github/searching-on-github/searching-issues-and-pull-requests) and also search for filename and code, could not surface this and the other closed PRs. How would you go about this? thanks.

**Comment by nateprewitt** [comment]
Searching either the function name "[check_compatibility](https://github.com/psf/requests/pulls?q=is%3Apr+check_compatibility+is%3Aclosed)" or phrase "[version check](https://github.com/psf/requests/pulls?q=is%3Apr+version+check+is%3Aclosed+)" like you've used will return the previous issues.

**Comment by oyeyipo** [comment]
confirmed :thumbsup: thanks

**Pull request closed without merging**
