### PR TITLE
Fix some issues to improve adherence to best practices

### PR DESCRIPTION
**Pull request by sanketsaurav**
Hi @kenneth-reitz,

I've fixed some style issues in the codebase to improve adherence to general best practices. 🚀 

These issues were highlighted when I ran a DeepSource analysis on my fork of requests. I've added the DeepSource config file as well, which can be used to connect requests to DeepSource -- so this analysis runs on every pull-request, which will make it easier to maintain quality on contributions. DeepSource is used by some popular open-source projects, like [uber/ludwig](https://deepsource.io/gh/uber/ludwig/). The product is, and will forever remain, free for open-source.

To connect requests and run analysis on every PR, there are three simple steps:
1. **Merge this PR.** I've added a customised `.deepsource.toml` for requests.
2. **Sign up on DeepSource** and grant access to this repository [here](https://deepsource.io/signup/).
3. **Activate analysis** on requests [here](https://deepsource.io/gh/kennethreitz/requests/).

*Disclaimer: I'm a co-founder of DeepSource. We use requests for our code of course, and would love to give back!*

### CODE REVIEW

**Comment by kennethreitz** [comment]
can you make these contributions to https://github.com/kennethreitz/requests3?

**Comment by sanketsaurav** [comment]
@kenneth-reitz Done! Please take a look at kennethreitz/requests3#15.

**Comment by LuckyDenis** [comment]
https://github.com/kennethreitz/requests/pull/5049

**Comment by nateprewitt** [comment]
Thanks @sanketsaurav. We typically won't take stylistic or layout change PRs. It looks like Kenneth merged kennethreitz/requests3#15 though, so I'll resolve this in favor of that one.

**Pull request closed without merging**
