### PR TITLE
Fixed #6683

### LINKED ISSUE #6683: raise_for_status documentation is out of sync
Not a bug per se, more like a discrepancy between documentation and actual behaviour.

## Expected Result

The [documentation](https://3.python-requests.org/user/quickstart/#response-status-codes) says `response.raise_for_status()` should return the response for chaining in trivial use cases.  

Screenshot from 2024-04-14 11-19-57

## Actual Result

The code in the latest version of package doesn't actually allow it, see [raise_for_status in models.py](https://github.com/psf/requests/blob/v2.31.0/requests/models.py#L994)

## Reproduction Steps

```
...
    response.raise_for_status().json()
AttributeError: 'NoneType' object has no attribute 'json'
```

### PR DESCRIPTION
**Pull request by ManiFaridi**
Since the documentation says that it should return a response object in case of no difficulties and the code didn't seem to, I added a statement to return the response object at the end.
[This is the issue](https://github.com/psf/requests/issues/6683)

### CODE REVIEW

**Review by dennyb87 — APPROVED** [review]
Looks good to me!

**Comment by dennyb87** [comment]
In hindsight perhaps a test wouldn't hurt

**Comment by ManiFaridi** [comment]
My bad, you are absolutely right. I'll get to it.

**Comment by dennyb87** [comment]
All good man :thumbsup: I don't have merge rights so can't really do much here anyway :smile: I raised it just in case :shrug:

**Comment by nateprewitt** [comment]
Thanks for the PR @ManiFaridi. This isn't something we'll likely be adding though, please refer to the original issue for more information.

**Pull request closed without merging**
