### PR TITLE
v2.28.1

### PR DESCRIPTION
**Pull request by nateprewitt**
2.28.1 (2022-06-29)
-------------------

**Improvements**

- Speed optimization in `iter_content` with transition to `yield from`. (#6170)

**Dependencies**

- Added support for chardet 5.0.0 (#6179)
- Added support for charset-normalizer 2.1.0 (#6169)

### CODE REVIEW

**Comment by nateprewitt** [comment]
I'm deferring the decisions on #6159 and #6167 until we see larger data points. They have 5 and 2 user engagements respectively which seems very low for the current 2.28.x adoption rate. For the time being, there are straight forward workarounds for both.

**Review by sethmlarson — APPROVED** [review]
Looks great, let's ship it! :shipit:

**Comment by afriedma** [comment]
> I'm deferring the decisions on #6159 and #6167 until we see larger data points. They have 5 and 2 user engagements respectively which seems very low for the current 2.28.x adoption rate. For the time being, there are straight forward workarounds for both.

Hi, what is the workaround for #6167? I am adding ":authority" and the request fails @nateprewitt

**Comment by nateprewitt** [comment]
@afriedma please keep conversations constrained to relevant issues. I believe this was already [answered](https://github.com/psf/requests/issues/6167#issuecomment-1159781034) in the other issue you commented on. If you're unfamiliar with PreparedRequests, you can find them in our [documentation](https://requests.readthedocs.io/en/latest/user/advanced/#prepared-requests).

**Pull request merged**
