### PR TITLE
Drop EOL Python 3.6

### PR DESCRIPTION
**Pull request by ofek**
See:

- https://endoflife.date/python
- https://www.python.org/dev/peps/pep-0494/#lifespan

### CODE REVIEW

**Comment by sigmavirus24** [comment]
We haven't even dropped 2.7. Please don't spam this project

**Comment by ofek** [comment]
@sigmavirus24 I know we haven't dropped Python 2, that won't happen until v3 AFAIU. Are you saying dropping EOL 3.x is blocked on dropping 2.7? I saw commits dropping [3.4](https://github.com/psf/requests/commit/68e581f1b5b4425a0ee950a2433fc3c92e671d0f) and [3.5](https://github.com/psf/requests/commit/f6c0619d892a41dcf84933810ffda89e9f6b10d4) which is why I thought it was alright to open this PR.

Also, I don't think it's quite right to characterize a contribution as spam. I came along and saw something that might need doing so I tried to help out (was going push a final commit to update docs files later today).

I understand there's a lot going on in the world right now though, so no worries.

**Comment by nateprewitt** [comment]
Hi @ofek,

We are planning to drop [Python 2.7](https://github.com/psf/requests/issues/6023) and 3.6 in the next minor release. We're currently keeping `main` clean for any other hotfix issues that may come in before that release. Thanks for contribution and we'll look at trying to pull some of this in when it's time.

**Comment by ofek** [comment]
@nateprewitt Oh that's awesome, thank you!

**Pull request closed without merging**
