### PR TITLE
Add PATCH example to the Quickstart of documentation

### PR DESCRIPTION
**Pull request by jeffreytse**
This PR mades users understand that the library supports the patch method and the simple use of it quickly.

### CODE REVIEW

**Comment by jeffreytse** [comment]
Hi @nateprewitt, this simple change will mean a whole lot for many new users to quickly use this library. I hope you have a good day! Thanks and regards. : D

**Comment by sethmlarson** [comment]
We aren't accepting small changes to the README.

**Comment by jeffreytse** [comment]
Hi @sethmlarson, it's not the README, it's the document, so I need to open another PR just for the document change?

**Comment by sethmlarson** [comment]
Either way, we're not accepting small changes to any documentation, we don't have the reviewer time to review and merge them all.

**Comment by jeffreytse** [comment]
But this very samll change on the quicklystart page makes the document completed and greatly improve people's time. Thanks and regards.
image

**Pull request closed without merging**
