### PR TITLE
Document how to turn off Keep-Alive in 2.x

### LINKED ISSUE #5646: Unable to turn off Keep-Alive
Documentation doesn't specify how to turn off Keep-Alive
https://requests.readthedocs.io/en/latest/user/advanced/#keep-alive

### PR DESCRIPTION
**Pull request by abitrolly**
Ref. #5646

### CODE REVIEW

**Comment by sigmavirus24** [comment]
This documentation isn't entirely correct and that issue is already clsoed

**Comment by abitrolly** [comment]
@sigmavirus24 I don't know how to improve it. What is not correct here?

**Comment by abitrolly** [comment]
I edited the description to mention issue without closing it (for me).

**Comment by sigmavirus24** [comment]
> What is not correct here?

It's not the only way to disable keep-alive. Sessions are not the only way people use this and the solution can be more generic without being specific because people who use this library generally understand the concept of headers and what the Keep-Alive setting in the Connection header is, which is why this doesn't need to be documented as desperately as you think

**Comment by abitrolly** [comment]
@sigmavirus24 it is needs to be documented, because in the past there were multiple ways to do this, which don't work now https://stackoverflow.com/questions/21008953/python-requests-1-how-to-disable-keep-alive

**Comment by abitrolly** [comment]
Reworded and moved to the paragraph about sessions.

**Comment by sigmavirus24** [comment]
> @sigmavirus24 it is needs to be documented, because in the past there were multiple ways to do this, which don't work now https://stackoverflow.com/questions/21008953/python-requests-1-how-to-disable-keep-alive

Information will always be outdated on the internet. Your initial commit was wrong immediately and is still overly specific to _your_ usecase. Beyond which, you seem to have (potentially deliberately) misunderstood my characterization of the urgency with the necessity

**Comment by nateprewitt** [comment]
I'm going to resolve this as there hasn't been any movement in the last year.

**Comment by abitrolly** [comment]
Killing keep alive literally.

**Pull request closed without merging**
