### PR TITLE
Don't mention pip as the reason for supporting py2

### PR DESCRIPTION
**Pull request by verhovsky**
since pip no longer supports Python 2

### CODE REVIEW

**Comment by verhovsky** [comment]
I don't know if that is actually the official plan, but I get the impression that that's what's going to happen from this comment https://github.com/psf/requests/pull/5660#issuecomment-729236559

**Comment by nateprewitt** [comment]
Hi @verhovsky, thanks for the PR. I'm not sure that comment was related to Python 2.7's deprecation. We had initially kept it as a requirement for `pip` but now that that's gone, we don't have a strong reason to keep it. It's just a matter of figuring out when we decide to formally stop Python 2.7 support. That likely won't happen before a major version bump of Requests.

If you'd like to replace the reference to `pip` with something more general like "and intend to maintain Python 2.7 support within Requests until otherwise announced.", I'm fine merging that.

**Comment by verhovsky** [comment]
@nateprewitt how about just removing that part? "We do not have immediate plans" and "[we] intend to maintain Python 2.7 support within Requests until otherwise announced" are basically saying the same thing twice.

**Review by nateprewitt — APPROVED** [review]
:+1: Great, I think this is fine for the time being. Thanks!

**Pull request merged**
