### PR TITLE
If they do't have same length, there is no need to create two dict to compare.

### PR DESCRIPTION
**Pull request by sunsongpy**

### CODE REVIEW

**Comment by nateprewitt** [comment]
Hi @sunsongpy, checks like [this](https://github.com/python/cpython/blob/109fc2792a490ee5cd8a423e17d415fbdedec5c8/Objects/dictobject.c#L2751) are baked into the base objects, so there’s no need for us to reimplement it here. Thanks for the suggestion!

**Comment by nateprewitt** [comment]
Apologies, I glanced over the PR too quickly. If you can provide benchmarks for this change showing a significant improvement, I think we can look at it. Otherwise, I think we’ll pass for now.

**Comment by sunsongpy** [comment]
> Apologies, I glanced over the PR too quickly. If you can provide benchmarks for this change showing a significant improvement, I think we can look at it. Otherwise, I think we’ll pass for now.

Sorry, I know this change won't bring much of a significant improvement, but  it certainly makes the code more rigorous. If the length is different, it's definitely False (two dict comparison of Cpython source code is the first step is to compare the length, why we don't do like that first).

**Comment by sunsongpy** [comment]
> Yes this can improve performance .

thanks

**Comment by shivareddyiirs** [comment]
> 
> 
> > Apologies, I glanced over the PR too quickly. If you can provide benchmarks for this change showing a significant improvement, I think we can look at it. Otherwise, I think we’ll pass for now.
> 
> Sorry, I know this change won't bring much of a significant improvement, but it certainly makes the code more rigorous. If the length is different, it's definitely False (two dict comparison of Cpython source code is the first step is to compare the length, why we don't do like that first).

After seeing the @nateprewit link . I agree with him. Adding extra lines of code just to do what is already being done, is not justified.

**Pull request closed without merging**
