### PR TITLE
Fix urllib3 pin in setup.cfg

### LINKED ISSUE #6544: Conflicting requirements for urllib3
In origin/main ee93fac6b2f7 I find conflicting required urllib3 version information:

```
setup.cfg:10:    urllib3>=1.21.1,<1.27
setup.py:64:    "urllib3>=1.21.1,<3",
```

Shouldn't both files have the same restrictions?

Best regards

Heinrich

### PR DESCRIPTION
**Pull request by nateprewitt**
This should resolve #6544.

### CODE REVIEW

**Comment by xypron** [comment]
LGTM, thanks for fixing.

**Comment by nateprewitt** [comment]
Currently blocked on Flask 3.0.0 issues. We'll need to get those fixed first.

**Comment by nateprewitt** [comment]
psf/httpbin#28

**Review by sethmlarson — APPROVED** [review]
LGTM!

**Comment by nateprewitt** [comment]
I've put up psf/httpbin#29 to address the test suite issues. We'll go ahead and merge this since I'm not concerned about the test suite with this change.

**Pull request merged**
