### PR TITLE
Fix build - use python 2.7 compatible super() call.

### PR DESCRIPTION
**Pull request by asherf**
Issue introduced here: https://github.com/psf/requests/pull/4983/files#diff-28e67177469c0d36b068d68d9f6043bfR425

### CODE REVIEW

**Comment by asherf** [comment]
@nateprewitt @kennethreitz friendly ping 🙏

**Comment by epenet** [comment]
@asherf, I think the first parameter should be the base class
```python
    super(SessionRedirectMixin, self).__init__()
```
not the current class
```python
    #Invalid
    super(Session, self).__init__()
```

Refs #5175

**Comment by asherf** [comment]
> @asherf, I think the first parameter should be the base class
> 
> ```python
>     super(SessionRedirectMixin, self).__init__()
> ```
> 
> not the current class
> 
> ```python
>     #Invalid
>     super(Session, self).__init__()
> ```
> 
> Refs #5175

@epenet I looked in several places in the code:
https://github.com/psf/requests/blob/master/requests/adapters.py#L59
https://github.com/psf/requests/blob/master/requests/adapters.py#L123
https://github.com/psf/requests/blob/master/requests/exceptions.py#L25
the pattern that you suggest doesn't seem the one that is being used....

also if you look at the [python docs](https://docs.python.org/2/library/functions.html#super), the example there uses the 'current' class:
```python
class C(B):
    def method(self, arg):
        super(C, self).method(arg)
```

**Comment by epenet** [comment]
Thanks @asherf, there's a lot of contradictory information on super() out there, so I'm happy with your change.

It would be good for @nateprewitt or @kennethreitz to merge it as it's currently upsettingTravis CI on all other PR.

**Comment by nateprewitt** [comment]
Hi @asherf, thanks for the PR. I’m not convinced we want the code that was merged in the referenced commit in the first place. I need to take a look through, see what testing would need to be added and what security implications it’s going to have.

I’ll leave this open until a decision is made but it’s likely we’ll revert the other commit.

**Comment by nateprewitt** [comment]
I've pushed 09fd857 to resolve the issue. Resolving in favor of that.

**Pull request closed without merging**
