### PR TITLE
Update documentation for response.json()

### PR DESCRIPTION
**Pull request by ellie**
The current documentation says that the function is encoding - actually, it is decoding!

I'm also wondering if it might be worth putting in some type annotations at some point

### CODE REVIEW

**Comment by alekna** [comment]
It doesn't return JSON body. It returns Python object.

Fixes #5245

**Comment by toothstone** [comment]
As long as this is open - I would like to add that the "if any" clause is very unclear, from the code I can't tell what is meant to say.

From what I can see the function tries to return the decoded representation *as if* the content were JSON - there are no checks if it actually is, is declared by the response to be, or even exists at all.

**Review by jimmysisonlucas — COMMENTED** [review]
Thanks for informing me

**Comment by sethmlarson** [comment]
I think we'll keep the current docstring, thanks!

**Pull request closed without merging**
