### PR TITLE
Make the `data` vs `json` parameters more clear

### PR DESCRIPTION
**Pull request by gdubicki**
As https://stackoverflow.com/q/26685248/2693875 question
and answer popularity shows that there is a lot of people who
do not understand the distinction.

### CODE REVIEW

**Comment by gdubicki** [comment]
Ping! Can I get a review, pretty please? :)

**Comment by hithwen** [comment]
Can we get this merged? I just lost half an hour on this

**Comment by Krogsager** [comment]
The current wording is counter intuitive, I recommend @gdubicki's PR.

**Review by abelcheung — COMMENTED** [review]
I'd also agree that the wording in PR is clearer than original one.

**Review by nateprewitt — APPROVED** [review]
Thanks for this, @gdubicki!

**Pull request merged**
