### PR TITLE
Fix calling get_connection() with a positional argument when it is optional

### PR DESCRIPTION
**Pull request by BoboTiG**

### CODE REVIEW

**Comment by sigmavirus24** [comment]
This says it's fixing something, but it's not strictly necessary and there's no context for why you feel this to be necessary. Can you elaborate?

**Comment by BoboTiG** [comment]
Oh sorry for the lack of details, it seems I closed my computer without having filled the description...

I subclassed the `HTTPAdapter` class, here is the revelant code: https://github.com/httpie/httpie-snapdsocket/blob/aa0d58beca2475b461ba9eac420fff5583e67bed/httpie_snapdsocket.py#L21
It works like a charm.

But then, I wanted to replace 
```python
def get_connection(self, url, proxies=None):
    # ...
    return super().get_connection(url, proxies=proxies)
```
with 
```python
def get_connection(self, url, **kwargs):
    # ...
    return super().get_connection(url, **kwargs)
```
To be resilient to future API updates on the `requests` side.

It will not work:
```python
Traceback (most recent call last):
  File "httpie-snapdsocket/tests.py", line 17, in test_simple
    res = session.get('snapd:///v2/find?name=' + package).json()
  File ".../site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File ".../requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File ".../site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File ".../site-packages/requests/adapters.py", line 412, in send
    conn = self.get_connection(request.url, proxies)
TypeError: get_connection() takes 2 positional arguments but 3 were given
```

I can live with it though.

**Comment by sigmavirus24** [comment]
> ```python
> def get_connection(self, url, **kwargs):
>     # ...
>     return super().get_connection(url, **kwargs)
> ```

Why not

```python
def get_connection(self, url, proxies=None, **kwargs):
    # ...
    kwargs.setdefault("proxies", proxies)
    return super().get_connection(url, **kwargs)
```

That achieves what you want without making a unnecessary change here

**Comment by BoboTiG** [comment]
The goal was to not care about `kwargs` at all. So that when/if the `get_connection()` signature changes, my code will still work.

**Comment by sigmavirus24** [comment]
It's incredibly unlikely to change

**Pull request closed without merging**
